CREATE TABLE IF NOT EXISTS trails (
    id SERIAL PRIMARY KEY,
    short TEXT NOT NULL,
    long TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expiration_hours INTEGER NOT NULL DEFAULT 1
);
