CREATE TABLE IF NOT EXISTS tracks (
    id SERIAL PRIMARY KEY,
    trail_id INTEGER NOT NULL,
    hashed_ip TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (trail_id) REFERENCES trails(id)
)
