name: CI

on:
  push:

env:
  POETRY_HOME: ${{ github.workspace }}/.poetry

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: ci
          POSTGRES_PASSWORD: ci
          POSTGRES_DB: ci
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U ci"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Poetry
        run: |
          pipx install poetry==2.1.3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'

      - name: Install dependencies
        run: |
          poetry install --no-interaction
          echo "$(poetry env info --path)/bin" >> $GITHUB_PATH

      - name: Run tests
        run: |
          pytest
        env:
          TINY_TRAILS_TEST_ADMIN_DB: postgresql://ci:ci@localhost:5432/ci
